export 'package:landing_page/UI/home_layout/web/views/home_view_sections/1.first_section/widgets/diagonal_background.dart';
export 'package:landing_page/UI/home_layout/web/views/home_view_sections/1.first_section/widgets/notice_box.dart';
export 'package:landing_page/UI/home_layout/web/views/home_view_sections/1.first_section/widgets/decoration_line.dart';
export 'package:landing_page/UI/home_layout/web/views/home_view_sections/1.first_section/widgets/column_welcome.dart';
export 'package:landing_page/UI/home_layout/web/views/home_view_sections/1.first_section/widgets/diagonal_clipper.dart';
export 'package:landing_page/UI/home_layout/web/views/home_view_sections/1.first_section/widgets/item_flotante.dart';
export 'package:landing_page/UI/home_layout/web/views/home_view_sections/1.first_section/widgets/lines_box.dart';
export 'package:landing_page/UI/home_layout/web/views/home_view_sections/1.first_section/widgets/lines_decoration.dart';
export 'package:landing_page/UI/home_layout/web/views/home_view_sections/1.first_section/widgets/text_welcome_barber.dart';
